name = "VPTrees"
uuid = "6889b67b-453b-53df-8fa8-6efd51eae556"
authors = ["Alan Schelten"]
version = "0.1.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.1.1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StringDistances", "Random"]
